CREATE OR REPLACE TABLE RAW_TITLES (
    SHOW_ID STRING,
    TYPE STRING,
    TITLE STRING,
    DIRECTOR STRING,
    CAST STRING,
    COUNTRY STRING,
    DATE_ADDED STRING,
    RELEASE_YEAR INT,
    RATING STRING,
    DURATION STRING,
    LISTED_IN STRING,
    DESCRIPTION STRING
);
